---
- name: set ulimit file
  sudo: yes
  copy: src=./limits.conf dest=/etc/security/limits.conf

- name: set net.core.somaxconn=32768
  sudo: yes
  sysctl: name=net.core.somaxconn value=32768 state=present

- name: set net.ipv4.tcp_max_syn_backlog=1024
  sudo: yes
  sysctl: name=net.ipv4.tcp_max_syn_backlog value=1024 state=present

- name: set net.ipv4.tcp_max_tw_buckets=2000000
  sudo: yes
  sysctl: name=net.ipv4.tcp_max_tw_buckets value=2000000 state=present

- name: set net.core.netdev_max_backlog=8192
  sudo: yes
  sysctl: name=net.core.netdev_max_backlog value=8192 state=present

- name: set net.ipv4.tcp_tw_reuse=1
  sudo: yes
  sysctl: name=net.ipv4.tcp_tw_reuse value=1 state=present

- name: set net.ipv4.tcp_fin_timeout=10
  sudo: yes
  sysctl: name=net.ipv4.tcp_fin_timeout value=10 state=present
