---
- name: update apt if needed
  sudo: yes
  apt: update_cache=yes cache_valid_time=36000

- name: install mysqlclient
  sudo: yes
  apt: name={{ item }} state=present
  with_items:
    - mysql-client
    - libmysqlclient-dev
